//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_kegiatan
    {
        public long keg_id { get; set; }
        public string keg_name { get; set; }
        public string keg_description { get; set; }
        public string keg_focus { get; set; }
        public long keg_volume { get; set; }
        public decimal keg_value { get; set; }
        public long prog_id { get; set; }
    }
}
