//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sosial
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_volunteer
    {
        public long vol_id { get; set; }
        public string vol_card_id { get; set; }
        public string vol_name { get; set; }
        public long wil_id { get; set; }
        public string vol_phone { get; set; }
        public string vol_address { get; set; }
        public string vol_occupation { get; set; }
        public long vol_email { get; set; }
        public int prog_id { get; set; }
    }
}
